console.log('Name: Austin Davis');
console.log('Career: Seeking a career in software development');
console.log('Description: Jack of all trades, master of none... yet');
console.log('');
console.log('My Interests:');
console.log('* Rock Climbing');
console.log('* Hiking');
console.log('* Acrobatics');
console.log('* Podcasts');
console.log('* World History');
console.log('');
console.log('My Previous Experience:');
console.log('* Staff intern at U.S. House of Representatives - Received and compiled constituent data, helped with legislative research, gave tours of the Capitol');
console.log('* MWD Field Engineer (Oil Field) - Operated and maintained high-tech equipment to determine direction of drilling, and to log underground geological data');
console.log('* Financial Relationship Consultant at Regions Bank - Provided customers with financial advice and bank products, helped achieve sales targets for the branch');
console.log('');
console.log('My Skills:');
console.log('* Coding experience from high school (C++, Java, assembly for TI-83+)');
console.log('* Strong communication skills');
console.log('* Guitar');
console.log('* BAM: Nunchuck skills');
console.log('* BAM: Bow-hunting skills');
console.log('* BAM: Computer hacking skills');
console.log('* ... Girls only like guys who have great skills');
